#!/usr/bin/env python3
"""Writes evidence/README.md from every run's summary.json, so each number
in this repository comes from a run and none is typed by hand."""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
EVIDENCE = ROOT / "evidence"
NAMES = {
    "android-emulator": "Pixel 7 emulator, Android 15",
    "ios-simulator": "iPhone 17 Pro simulator, iOS 26.5",
    "android-phone": "Pixel 8 Pro, Android 17",
    "iphone": "iPhone 15 Plus, iOS 26.6.2",
}


def link(run, name, label):
    return f"[{label}]({run.name}/{name})" if (run / name).exists() else "—"


rows, detail = [], []
for run in sorted(p for p in EVIDENCE.iterdir() if (p / "summary.json").exists()):
    s = json.loads((run / "summary.json").read_text())
    device = NAMES.get(s["device"], s["device"])
    poll = s["act4"]["poll_refused_after_ms"] / 1000
    rows.append(
        f"| {device} | {s['act1']['row_b']} | {s['act2']['row_b']} — {s['act2']['tap']} "
        f"| {s['act3']['flaky']} | {s['act3']['steady']} | refused after {poll:.1f} s |"
    )
    files = [
        link(run, "transcript.md", "transcript"),
        link(run, "act1-vs-act2.mp4", "side by side"),
        link(run, "act1.mp4", "act 1 video"), link(run, "act2.mp4", "act 2 video"),
        link(run, "act1.zip", "act 1 trace"), link(run, "act2.zip", "act 2 trace"),
        link(run, "act4.zip", "act 4 trace"),
        link(run, "act1-after-tap.png", "act 1 screen"), link(run, "act2-after-tap.png", "act 2 screen"),
        link(run, "report-flaky/index.html", "flaky report"), link(run, "report-steady/index.html", "steady report"),
    ]
    detail.append(f"- **{device}** (`{run.name}`): " + " · ".join(f for f in files if f != "—"))

out = ["# Evidence", "",
       "Generated by `scripts/summarize.py` from each run's `summary.json`; every run is",
       "`scripts/demo.sh` on one device. Traces open at https://player.vibium.dev.", "",
       "| Device | Act 1: Row B, launched normally | Act 2: Row B, with `--gray-box` | Act 3: flaky | Act 3: steady | Act 4: polling forever |",
       "| --- | --- | --- | --- | --- | --- |", *rows, "", "## Files", "", *detail, ""]
(EVIDENCE / "README.md").write_text("\n".join(out))
print(f"evidence/README.md: {len(rows)} runs")
