#!/usr/bin/env python3
"""Writes evidence/README.md from every run's summary.json, so each number
in this repository comes from a run and none is typed by hand."""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
EVIDENCE = ROOT / "evidence"
NAMES = {
    "android-emulator": "Pixel 7 emulator, Android 15",
    "ios-simulator": "iPhone 17 Pro simulator, iOS 26.5",
    "android-phone": "Pixel 8 Pro, Android 17",
    "iphone": "iPhone 15 Plus, iOS 26.6.2",
}


def link(run, name, label):
    return f"[{label}]({run.name}/{name})" if (run / name).exists() else "—"


ORDER = ["android-emulator", "android-phone", "ios-simulator", "iphone"]


def key(run_summary):
    run, s = run_summary
    return (ORDER.index(s["device"]) if s["device"] in ORDER else 9, run.name)


runs = [(p, json.loads((p / "summary.json").read_text()))
        for p in sorted(EVIDENCE.iterdir()) if (p / "summary.json").exists()]
acts = sorted(((r, s) for r, s in runs if "act1" in s), key=key)
hooks = sorted(((r, s) for r, s in runs if "act5" in s), key=key)

rows, detail = [], []
for run, s in acts:
    device = NAMES.get(s["device"], s["device"])
    poll = s["act4"]["poll_refused_after_ms"] / 1000
    rows.append(
        f"| {device} | {s['act1']['row_b']} | {s['act2']['row_b']} — {s['act2']['tap']} "
        f"| {s['act3']['flaky']} | {s['act3']['steady']} | refused after {poll:.1f} s |"
    )
    files = [
        link(run, "transcript.md", "transcript"),
        link(run, "act1-vs-act2.mp4", "side by side"),
        link(run, "act1.mp4", "act 1 video"), link(run, "act2.mp4", "act 2 video"),
        link(run, "act1.zip", "act 1 trace"), link(run, "act2.zip", "act 2 trace"),
        link(run, "act4.zip", "act 4 trace"),
        link(run, "act1-after-tap.png", "act 1 screen"), link(run, "act2-after-tap.png", "act 2 screen"),
        link(run, "report-flaky/index.html", "flaky report"), link(run, "report-steady/index.html", "steady report"),
    ]
    detail.append(f"- **{device}** (`{run.name}`): " + " · ".join(f for f in files if f != "—"))

hook_rows, hook_detail = [], []
for run, s in hooks:
    device = NAMES.get(s["device"], s["device"])
    a = s["act5"]
    first = lambda text: text.splitlines()[0] if text else ""
    hook_rows.append(
        f"| {device} | {a['toast_shown']} | {a['raise_toast_ms'] / 1000:.1f} s | {a['toast_unicode']} "
        f"| {a['welcome']} | {first(a['typo']).removeprefix('error: ')} |"
    )
    files = [
        link(run, "transcript.md", "transcript"), link(run, "act5.mp4", "video"),
        link(run, "act5.zip", "trace"), link(run, "toast.png", "toast"),
        link(run, "toast-unicode.png", "non-ASCII toast"), link(run, "signed-in.png", "signed in"),
    ]
    hook_detail.append(f"- **{device}** (`{run.name}`): " + " · ".join(f for f in files if f != "—"))

out = ["# Evidence", "",
       "Generated by `scripts/summarize.py` from each run's `summary.json`. Acts 1 to 4",
       "are `scripts/demo.sh` on one device, act 5 is `scripts/hooks.sh`. Traces open",
       "at https://player.vibium.dev.", "",
       "| Device | Act 1: Row B, launched normally | Act 2: Row B, with `--gray-box` | Act 3: flaky | Act 3: steady | Act 4: polling forever |",
       "| --- | --- | --- | --- | --- | --- |", *rows, "",
       "## Act 5: hooks", "",
       "`mobium hook raiseToast \"Toast raised by test script\"`, and what the app showed. A call's",
       "time includes the gray box's wait for the app to be idle first.", "",
       "| Device | The app's toast | The call took | A non-ASCII toast | `signIn mobium` | A typo |",
       "| --- | --- | --- | --- | --- | --- |", *hook_rows, "",
       "## Files", "", *detail, *hook_detail, ""]
(EVIDENCE / "README.md").write_text("\n".join(out))
print(f"evidence/README.md: {len(rows)} runs of acts 1 to 4, {len(hook_rows)} of act 5")
